-- Fix default account passwords for all 4 roles
-- All accounts use password: DTech@150102
-- BCrypt $2a$ hash generated by Spring Security BCryptPasswordEncoder

-- 1. SUPER_ADMIN: admin / DTech@150102
UPDATE users SET password_hash = '$2a$10$1rU6pLckwVZ99/zRcfc6VOpeYl08BW9UJSVAGbcRZJMpFP8ip2.YO'
WHERE username = 'admin';

-- 2. SUPER_ADMIN (backup): superadmin / DTech@150102
UPDATE users SET password_hash = '$2a$10$1rU6pLckwVZ99/zRcfc6VOpeYl08BW9UJSVAGbcRZJMpFP8ip2.YO'
WHERE username = 'superadmin';

-- 3. TENANT_MANAGER: manager / DTech@150102
UPDATE users SET password_hash = '$2a$10$1rU6pLckwVZ99/zRcfc6VOpeYl08BW9UJSVAGbcRZJMpFP8ip2.YO'
WHERE username = 'manager';

-- 4. GUARD: guard / DTech@150102
UPDATE users SET password_hash = '$2a$10$1rU6pLckwVZ99/zRcfc6VOpeYl08BW9UJSVAGbcRZJMpFP8ip2.YO'
WHERE username = 'guard';

-- 5. TENANT: tenant / DTech@150102
UPDATE users SET password_hash = '$2a$10$1rU6pLckwVZ99/zRcfc6VOpeYl08BW9UJSVAGbcRZJMpFP8ip2.YO'
WHERE username = 'tenant';
